### ISSUE TITLE
[#0022] Reuniões de parcerias deletadas

### ISSUE THREAD

**Issue by drisabelles** [The-Bugger-Ducks/owl-partners-back#41]
## 📄 Descrição da atividade

Em uma parceria deletada, deve somente exibir a lista de todas as reuniões que ocorreram (equivalente a Últimas Reuniões na parceria ativa).

Não deve ser possível acessar os detalhes dessas reuniões.

## 🛠 Protótipo

![Image](https://user-images.githubusercontent.com/78885451/236333965-13ead9e3-5087-46ae-a246-b6145d2ba156.png)

### DoR: Definition of Ready

- [x] **Cabe em uma sprint:** De preferência, não deve ser maior que 8 story points
- [x] **Prototipado:** O protótipo já está disponível no [Figma](https://www.figma.com/file/OfE7DUkKkBgC7O3fmDoulH/Owl-Partners-(Oracle)?node-id=11-195&t=txTFGhY0EvM3VWcn-0)
- [x] **Validado com o cliente:** As informações da atividade foram validadas pelo cliente

### Critérios de aceite

- [x] Deve ser possível vizualizar uma lista de reuniões ocorridas (Últimas reuniões)
- [x] As reuniões que estariam marcadas para datas após a inativação devem ser excluídas.

### DoD: Definition of Done

- [x] **Atende aos critérios de aceite:** Todos os critérios de aceite definidos para a atividade foram cumpridos
- [x] **Code review:** O code review foi realizado e, se identificada a necessidade, as correções foram realizadas
- [x] **Testado e integrado:** A feature desenvolvida já se encontra na branch Development e funciona em harmonia com as demais funcionalidades (navegação em funcionamento, não gerou bugs, conflitos foram resolvidos)
- [x] **Documentado:** A feature desenvolvida foi documentada pelo desenvolvedor
- [ ] **Aceito pelo PO:** A feture desenvolvida foi aprovada pelo PO

**Comment by gioliveirass** [comment]
Em validação.

**Comment by gioliveirass** [comment]
Validado.

**Comment by gioliveirass** [comment]
Pode ser excluída.

**Comment by ThHenrique** [comment]
# Documentação

## Task
#41 

## Tecnologias
NestJS, Prisma, PostgresSQL, Insomnia, VSCODE, beekeeper Studio portable

### Reuniões agendadas.
Reuniões
![image](https://github.com/The-Bugger-Ducks/owl-partners-back/assets/58437896/221010f9-e42a-42ce-a76a-391617388e9e)

### Desativando parceria.
![image](https://github.com/The-Bugger-Ducks/owl-partners-back/assets/58437896/6b499d39-b4f2-4cd9-9a1b-f7088ea9c0ac)

### Reuniões agendadas de uma parceiria desativada excluídas
![image](https://github.com/The-Bugger-Ducks/owl-partners-back/assets/58437896/ab343cf6-d6b4-442b-a743-c73d89103d91)

---
**URL**: domain.api.com.br//partners/:id
**Method**: DELETE

- Controller 
```typescript
	@Delete('/:id')
	@UseGuards(AuthGuard('jwt'))
	async disablePartner(@Param('id') id: string) {
		const partnerFound = await this.partnerService.findById(id);

		if (partnerFound === null) {
			throw new NotFoundException('Parceria não encontrada.');
		}

		await this.partnerService.deleteUpcomingMeetings(id);
		await this.partnerService.disable(id);

		return { message: 'Parceria desativada com sucesso.' };
	}
```

- Service Partner
```typescript
deleteUpcomingMeetings(id: string) {
		return this.meetingService.deleteUpcomingMeetingsByPartnerId(id);
	}
```

- Service Meeting
```typescript
	deleteUpcomingMeetingsByPartnerId(partnerId: string) {
		return this.prismaService.meeting.deleteMany({
			where: {
				partnerId: partnerId,
				meetingDateTime: {
					gt: getCurrentBrDateTimeISO(),
				},
			},
		});
	}
```

**Comment by drisabelles** [comment]
@gioliveirass
